import {StyleSheet} from 'react-native';

const StylesButton = StyleSheet.create({
    btnText: { textAlign: 'center', color: '#fff' },
    buttonIconHome: {
        flex:0.1,
        backgroundColor: '#18181bcc',       
    },
    btn: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.30,
        shadowRadius: 4.65,
        elevation: 8,
        display: 'flex',
        position: 'absolute',
        backgroundColor:  "#142950",
        justifyContent: 'center',
        alignItems: 'center',
        width: 50,
        height: 50,
        borderRadius: 70,
        bottom: 5,
        right: 10,
    },
    btnText: {textAlign: 'center', color: '#ADFF2F', marginLeft: 20, fontSize: 25},
    btnTextCities: {textAlign: 'center', color: '#ADFF2F', fontSize: 15},
    btnTextAddCity: {textAlign: 'center', color: '#ADFF2F', fontSize: 25},    
    btnAddCity: {textAlign: 'center', color: '#ADFF2F', fontSize: 25, left: 100,
                    backgroundColor:  "#142950", borderRadius: 70, marginTop: 30,
                    width: 145, height: 40, },
    btnCity: {shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.30,
        shadowRadius: 4.65,
        elevation: 8,
        display: 'flex',
        position: 'absolute',
        backgroundColor:  "#142950",
        justifyContent: 'center',
        alignItems: 'center',
        width: 50,
        height: 50,
        borderRadius: 70,
        bottom: 5,
        right: 10,
    },
    btnCities: {shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.30,
        shadowRadius: 4.65,
        elevation: 8,
        display: 'flex',
        position: 'absolute',
        backgroundColor:  "#142950",
        justifyContent: 'center',
        alignItems: 'center',
        width: 50,
        height: 50,
        borderRadius: 70,
        bottom: 5,
        right: 70,},
    btnHome: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.30,
        shadowRadius: 4.65,
        elevation: 8,
        display: 'flex',
        position: 'absolute',
        backgroundColor: "#142950",
        justifyContent: 'center',
        alignItems: 'center',
        width: 50,
        height: 50,
        borderRadius: 70,
        bottom: 5,
        right: 10,
    },
    btnClime: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.30,
        shadowRadius: 4.65,
        elevation: 8,
        display: 'flex',
        position: 'absolute',
        backgroundColor: "#142950",
        justifyContent: 'center',
        alignItems: 'center',
        width: 50,
        height: 50,
        borderRadius: 70,
        bottom: 5,
        right: 10,
    },
    btnDeleteStorage:{
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.30,
        shadowRadius: 4.65,
        elevation: 8,
        display: 'flex',
        position: 'absolute',
        backgroundColor: "#142950",
        justifyContent: 'center',
        alignItems: 'center',
        width: 50,
        height: 50,
        borderRadius: 70,
        bottom: 5,
        right: 150,
    },
})

export default StylesButton;